name: ci

on:
  push: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: titi
        uses: actions/checkout@v4
      
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME1 }}
          password: ${{ secrets.DOCKER_PASSWORD1 }}
      
      - name: Build et Push
        run: |
          docker build -t davidbekale/TP-DOCKER/api/davidbekale/mon-api:latest 
          docker push davidbekale/TP-DOCKER/api/davidbekale/mon-api:latest
      
      - name: Build et Push
        run: |
          docker build -t davidbekale/TP-DOCKER/front/davidbekale/mon-image:latest 
          docker push davidbekale/TP-DOCKER/front/davidbekale/mon-image:latest